{"name": "test_user_login_DDT_005", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: '..\\\\testCases\\\\Test_Data\\\\Test_Data.xlsx'", "trace": "self = <testCases.test_UserLogin_DDT.Test_Login_DDT object at 0x0000022ED0ECE690>\nsetup = <selenium.webdriver.firefox.webdriver.WebDriver (session=\"d84ccd14-778c-485d-bf19-1eeef6c3d5ac\")>\n\n    @allure.severity(allure.severity_level.NORMAL)\n    @pytest.mark.sanity\n    def test_user_login_DDT_005(self, setup):\n        self.log.info(\"Test_case test_user_login_DDT_005 is started\")\n        self.driver = setup\n        self.log.info(\"Opening browser and navigating to demo_nop_com\")\n        self.lp = LoginClass(self.driver)\n>       self.rows = ExcelMethods.numRows(self.Excel_File_Path, 'LoginData')  # 5\n\ntestCases\\test_UserLogin_DDT.py:25: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nutilities\\ExcelMethods.py:5: in numRows\n    Excel_File = openpyxl.load_workbook(file_name)  # loading the file\nvenv\\Lib\\site-packages\\openpyxl\\reader\\excel.py:344: in load_workbook\n    reader = ExcelReader(filename, read_only, keep_vba,\nvenv\\Lib\\site-packages\\openpyxl\\reader\\excel.py:123: in __init__\n    self.archive = _validate_archive(fn)\nvenv\\Lib\\site-packages\\openpyxl\\reader\\excel.py:95: in _validate_archive\n    archive = ZipFile(filename, 'r')\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <zipfile.ZipFile [closed]>\nfile = '..\\\\testCases\\\\Test_Data\\\\Test_Data.xlsx', mode = 'r', compression = 0\nallowZip64 = True, compresslevel = None\n\n    def __init__(self, file, mode=\"r\", compression=ZIP_STORED, allowZip64=True,\n                 compresslevel=None, *, strict_timestamps=True, metadata_encoding=None):\n        \"\"\"Open the ZIP file with mode read 'r', write 'w', exclusive create 'x',\n        or append 'a'.\"\"\"\n        if mode not in ('r', 'w', 'x', 'a'):\n            raise ValueError(\"ZipFile requires mode 'r', 'w', 'x', or 'a'\")\n    \n        _check_compression(compression)\n    \n        self._allowZip64 = allowZip64\n        self._didModify = False\n        self.debug = 0  # Level of printing: 0 through 3\n        self.NameToInfo = {}    # Find file info given name\n        self.filelist = []      # List of ZipInfo instances for archive\n        self.compression = compression  # Method of compression\n        self.compresslevel = compresslevel\n        self.mode = mode\n        self.pwd = None\n        self._comment = b''\n        self._strict_timestamps = strict_timestamps\n        self.metadata_encoding = metadata_encoding\n    \n        # Check that we don't try to write with nonconforming codecs\n        if self.metadata_encoding and mode != 'r':\n            raise ValueError(\n                \"metadata_encoding is only supported for reading files\")\n    \n        # Check if we were passed a file-like object\n        if isinstance(file, os.PathLike):\n            file = os.fspath(file)\n        if isinstance(file, str):\n            # No, it's a filename\n            self._filePassed = 0\n            self.filename = file\n            modeDict = {'r' : 'rb', 'w': 'w+b', 'x': 'x+b', 'a' : 'r+b',\n                        'r+b': 'w+b', 'w+b': 'wb', 'x+b': 'xb'}\n            filemode = modeDict[mode]\n            while True:\n                try:\n>                   self.fp = io.open(file, filemode)\nE                   FileNotFoundError: [Errno 2] No such file or directory: '..\\\\testCases\\\\Test_Data\\\\Test_Data.xlsx'\n\nC:\\Users\\HP\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\zipfile.py:1284: FileNotFoundError"}, "attachments": [{"name": "log", "source": "13bee803-93ed-40f4-a011-8dc1209e96a3-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "2e4aae36-880f-40ad-9cd5-caedc218f1ad-attachment.txt", "type": "text/plain"}], "start": 1707185166496, "stop": 1707185166646, "uuid": "873563ea-abb2-4f3e-994e-74a35e84d735", "historyId": "e76a33904762e396e94210de9cad9be6", "testCaseId": "e76a33904762e396e94210de9cad9be6", "fullName": "testCases.test_UserLogin_DDT.Test_Login_DDT#test_user_login_DDT_005", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "sanity"}, {"name": "parentSuite", "value": "testCases"}, {"name": "suite", "value": "test_UserLogin_DDT"}, {"name": "subSuite", "value": "Test_Login_DDT"}, {"name": "host", "value": "Tushar-Pc"}, {"name": "thread", "value": "36640-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testCases.test_UserLogin_DDT"}]}